pipeline {
    agent any

    stages {
        stage("Build") {
            steps {
                echo "Hello world!"
            }
        }

        stage("deploy"){
          steps{
            input message:"发布或停止"
          }
        }
    }
}